news/main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns = [
    path('', views.home, name="home"),
    path('all-news', views.all_news, name='all-news'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('all-category', views.all_category, name='all-category'),
    path('category/<int:id>', views.category, name="category"),
    path('register', views.registerPage, name='register'),
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('profile', views.proflie, name='profile')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/news/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

news/main/models.py
from django.db import models

class Category(models.Model):
    title = models.CharField(max_length=200)
    category_image = models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title
class News(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    image = models.ImageField(upload_to='imgs/')
    detail = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'News'

    def __str__(self):
        return self.title
class Comments(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=200)
    comment = models.TextField()
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.comment

news/main/forms.py
import re
from django.forms import ModelForm
#from .models import Order
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

# class OrderForm(ModelForm):
#     class Meta:
#         model = Order
#         fields = '__all__'


class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # add a custom validator to the password field
        self.fields['password1'].validators.append(
            self.validate_password_contains_number
        )

    def validate_password_contains_number(self, value):
        if not any(char.isdigit() for char in value):
            raise ValidationError('The password must contain at least one number.')
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    def clean_password1(self):
        password = self.cleaned_data.get('password1')
        if not re.search(r'[A-Z]', password):
            raise forms.ValidationError('Password must contain at least one uppercase letter.')
        return password
   

news/main/views.py
from django import forms
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
import re
from .models import *
from django.contrib import messages
from .forms import  CreateUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def registerPage(request):
    form = CreateUserForm()


    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            pas1 = form.cleaned_data.get('password1')
            pas2 = form.cleaned_data.get('password2')
            messages.success(request, 'Account was created for '+ user)
            print('good')
            return redirect('login')
    context = {'form': form}
    return render(request, 'accounts/register.html', context)

def loginPage(request):

    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username,password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request,'Username OR password is incorrect')

    context = {}
    return render(request,'accounts/login.html', context)
def logoutUser(request):
    logout(request)
    return redirect('login')
def home(request):
    first_news = News.objects.first()
    three_news = News.objects.all()[1:5]
    three_categories = Category.objects.all()[0:3]
    return render(request,'home.html',{
        'first_news':first_news,
        'three_news':three_news,
        'three_categories':three_categories
    })
def all_news(request):
    query = request.GET.get('q')  # Get the search query from the URL parameter 'q'
    all_news = News.objects.all()

    if query:
        all_news = all_news.filter(title__icontains=query)  # Filter the news by the search query

    return render(request, 'all-news.html', {
        'all_news': all_news,
        'query': query  # Pass the query back to the template for display
    })

def detail(request, id):
    news = News.objects.get(pk=id)
    if request.method=='POST':
        name = request.POST['name']
        email = request.POST['email']
        comment = request.POST['message']
        Comments.objects.create(
            news=news,
            name=name,
            email=email,
            comment=comment
        )
        messages.success(request, 'Comment sended successfully')
    rel_news = News.objects.filter(category=news.category).exclude(id=id)
    comments = Comments.objects.filter(news=news,status=True).order_by('-id')
    return render(request, 'detail.html', {
        'news':news,
        'related_news':rel_news,
        'comments':comments
    })
def all_category(request):
    cats = Category.objects.all()
    return render(request, 'category.html',{
        'cats':cats
    })
def category(request, id):
    category = Category.objects.get(pk=id)
    news = News.objects.filter(category=category)
    return render(request, 'category-news.html', {
        'all_news':news,
        'category':category,
    })

def proflie(request):
    if request.user.is_authenticated:
        return render(request, 'profile.html')
    else:
        return redirect('login')

news/main/templates/accounts/login.html
<!DOCTYPE html>
<html>

  <head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
      body,
      html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: RGB(52,58,64) !important;
      }

      .user_card {
        width: 350px;
        height: 400px;
        margin-top: auto;
        margin-bottom: auto;
        background: #74cfbf;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;
        background-color: RGB(52,58,64);

      } .tima{
        color: #ffffff;
              }

      .form_container {
        margin-top: 20px;
      }

      #form-title {
        color: #fff;

      }

      .login_btn {
        width: 100%;
        background: #fff !important;
        color: RGB(52,58,64) !important;
      }

      .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
      }

      .login_container {
        padding: 0 2rem;
      }

      .input-group-text {
        background: RGB(52,58,64) !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
      }

      .input_user,
      .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
      }
      a{
			text-decoration: None;
			color: #ffffff;
		}

      #messages {
        background-color: grey;
        color: #fff;
        padding: 10px;
        margin-top: 10px;
      }

    </style>

  </head>

  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">


            <h3 id="form-title">LOGIN</h3>
          </div>
          <div class="d-flex justify-content-center form_container">
            <form method="POST" action="">
              {% csrf_token %}
              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <input type="text" name="username" placeholder="Username..." class="form-control">
              </div>
              <div class="input-group mb-2">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-key"></i></span>
                </div>
                <input type="password" name="password" placeholder="Password..." class="form-control">
              </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Login">
              </div>
            </form>

          </div>
                {% for message in messages %}
					<p style="color: white" id="messages">{{message}}</p>
				{% endfor %}
          <div class="mt-4">
            <div class="d-flex justify-content-center links">
              <p class="tima">Zhanadan keldiniz be? <a href="{% url 'register' %}" class="ml-2">Tirkelu</a></p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </body>

</html>

news/main/templates/accounts/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: RGB(52,58,64) !important;
		}
		.user_card {
			width: 500px;
			height: 500px;
			margin-top: auto;
			margin-bottom: auto;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;
			background-color: RGB(52,58,64);


		}
		.tima{
			color: #ffffff;
		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #fff !important;
			color: RGB(52,58,64) !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: RGB(52,58,64) !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		a{
			text-decoration: None;
			color: #ffffff;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				{{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						<p class="tima">Buryn bizde boldynyz ba? <a href="{% url 'login' %}" class="ml-2">Kiru</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

news/main/templates/all-news.html
{% extends 'base.html' %}
{% block content %}

<main style="padding-top: -80px" class="container mt-3 mb-5">
    <!-- Search form -->
    <form class="form-inline mb-3" action="{% url 'all-news' %}" method="GET">
        <div class="form-group">
            <input type="text" class="form-control" name="q" placeholder="Search by News title" value="{{ query }}">
        </div>
        <button type="submit" class="btn btn-dark ml-2">Izdeu</button>
    </form>

    <!-- Rest of your template code -->

</main>

<main class="container mt-3 mb-5">

	<h3 class="border-bottom pb-1 my-4">Barlyq Zhanalyqtar</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-dark">Tolyqtai Oqu</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
	<br>
	<p></p>
</main>
{% endblock %}

news/main/templates/base.html
{% load static %}
<html lang="en">
<head>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Arvo&display=swap" rel="stylesheet">
	<title>{% block title %}Home Page{% endblock %}</title>
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
	<!-- Bootstrap Js -->
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
</head>
<body>
	<!-- Top News -->
	<style>
        .qw{

        }
        body{

font-family: 'Arvo', serif;
        }
    .madi{
        margin-bottom: 200px;
        background-color: #0f6674;
    }
    nav{
        padding-bottom: -100px;
    }
	.tima{
		color: red;
		margin-top: 7px;
	}
    .timon{
        margin-bottom: -100px;
    }
	</style>
    <br>

    <div class="timon">
	<nav class="navbar navbar-expand-lg navbar-light bg-white">
        <a href="/"><h3  class="navbar-brand tima" >zhanaLyq</h3></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a style="color: black" class="btn" href="/">Basty Bet</a>
      </li>
      <li class="nav-item">
        <a style="color: black" class="btn" href="{% url 'all-news' %}">Barlyq Zhanalyqtar</a>
      </li>
      <li class="nav-item">
        <a style="color: black" class="btn" href="{% url 'all-category' %}">Barlyq Categoriyalar</a>
      </li>
      {% if user.is_authenticated %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'logout' %}">Shygu</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item active"><a style="color: black" class="btnn" href="{% url 'login'  %}">Kiru</a></li>
        {% endif %}
    </ul>
  </div>
</nav>

	<hr style="margin-bottom: 100px; padding-bottom: -200px;" class="madi">
    {% block content %}
    {% endblock %}

</div>
</body>
</html>

news/main/templates/category-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail|truncatewords:18}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-dark">Tolyqtai Oqu</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
	<br>
</main>
{% endblock %}

news/main/templates/category.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Barlyq Categoriyalar</h3>
	<div class="row">
		<!-- Category Box -->
		{% for cat in cats %}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
            <img src="/media/{{cat.category_image}}" class="card-img-top" alt="{{cat.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{cat.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-dark">Tolyqtai Oqu</a></p>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
{% endblock %}

news/main/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text">{{news.detail}}</p>
			  </div>
			  <div class="card-footer bg-dark">
			  	<a style="color: white" href="/category/{{news.category.id}}">{{news.category.title}}</a>
			  </div>
			</div>

			<!-- Comments -->
			<div class="card my-4">
				<h6 class="card-header">Pikir qaldyru</h6>
				<div class="card-body">
					{% for message in messages %}
					<p class="text-success">{{message}}</p>
					{% endfor %}
					<form method="post" action="/detail/{{news.id}}">
						{% csrf_token %}
						<div class="form-group row">
							<label class="col-md-2">Esim<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="text" name="name" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Email<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="temailext" name="email" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Pikir<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<textarea class="form-control" name="message" required></textarea>
							</div>
						</div>
						<input type="submit" class="btn btn-dark" value="Zhiberu"/>
					</form>
				</div>
			</div>
			<!-- Previous Comments -->
			<div class="card my-4">
				<h6 class="card-header">Pikirler</h6>
				<div class="card-body">
					{% for comment in comments %}
					<blockquote class="blockquote text-right">
					  <p class="mb-0">{{comment.comment}}</p>
					  <footer class="blockquote-footer">{{comment.name}} <cite title="Source Title">{{comment.email}}</cite></footer>
					</blockquote>
					<hr/>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">Dal Osy Categoriyadan</h3>
			<!-- Category Box -->
			{% for news in related_news %}
			<div class="card mb-3 shadow">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
					<p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-dark">Tolyqtai Oqu</a></p>
			  </div>
			</div>
			{% endfor %}
		</div>
	</div>
</main>
{% endblock %}

news/main/templates/home.html
{% extends 'base.html' %}
{% block content %}
<main style="padding-top: -80px" class="container mt-3 mb-5">
	<!-- featured news -->
	<div  class="row my-3">
		<!-- Left -->
		<div class="col-md-12">
			<h3>Songy Zhanalyqtardan...</h3>
			<div class="card mb-3" style="height: 50%">
			  <img src="/media/{{first_news.image}}"  class="card-img-top" alt="{{first_news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-dark">Tolyqtai Oqu</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
<!--		<div class="col-md-5" style="max-height: 510px; overflow: auto;">-->
<!--			{% for news in three_news %}-->
<!--			&lt;!&ndash; News Box &ndash;&gt;-->
<!--			<div class="card">-->
<!--			  <div class="row no-gutters">-->
<!--			    <div class="col-md-4">-->
<!--					<img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">-->
<!--			    </div>-->
<!--			    <div class="col-md-8">-->
<!--			      <div class="card-body">-->
<!--			        <p class="card-title">{{news.title|truncatewords:5}}</p>-->
<!--			        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-dark">Tolyqtai Oqu</a></p>-->
<!--			      </div>-->
<!--			    </div>-->
<!--			  </div>-->
<!--			</div>-->
<!--			<hr/>-->
<!--			{% endfor %}-->
<!--		</div>-->
	</div>
	<br>
	<br>
	<!-- Category Wise News -->
	{% for category in three_categories %}
	<h3 class="border-bottom pb-1">{{category.title}} <a href="/category/{{category.id}}" class="float-right btn btn-sm btn-dark	 ">Dal osy categoriyadan</a></h3>
	<br>
	<div class="row my-4">
		{% for news in category.news_set.all %}
			{% if forloop.counter < 4 %}
			<!-- News box -->
			<div class="col-lg-4">
				<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<br>
					<hr/>
					<p class="card-text" ><a href="/detail/{{news.id}}" class="btn btn-sm btn-dark">Tolyqtai Oqu</a></p>
				</div>
				</div>
			</div>

			{% endif %}
		{% endfor %}
	</div>
	{% endfor %}
	<!-- End Single Category -->
</main>
{% endblock %}

news/main/templates/profile.html
{% extends 'base.html' %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="/static/login.css">
    <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
</head>
<body>
    <header>
<!--        <a href="index.html" class="logo">Logo</a>-->
    </header>


    <main>
        <!-- Content changes here -->
        <div class="container">
            <h2>Login</h2>
                <form action="view.html" class="form-container">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" placeholder="username">

                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" placeholder="password">

                    <button type="submit">Login</button>
                </form>
                <hr>
            <p>Don't have an account? <a href="signup.html">Sign Up</a> </p>
        </div>
        <!-- Content changes end here -->
    </main>
</body>
</html>

{% endblock %}